/*global systemDictionary:true */
"use strict";

systemDictionary = {
  "Server URL": {
    en: "Server URL",
    de: "Server-URL",
    ru: "URL сервера",
    pt: "URL do Servidor",
    nl: "Server-URL",
    fr: "URL du Serveur",
    it: "URL del Server",
    es: "URL del Servidor",
    pl: "Adres URL Serwera",
    uk: "URL-адреса сервера",
    "zh-cn": "服务器 URL",
  },
  "Authentication Type": {
    en: "Authentication Type",
    de: "Authentifizierungstyp",
    ru: "Тип аутентификации",
    pt: "Tipo de Autenticação",
    nl: "Verificatietype",
    fr: "Type d'authentification",
    it: "Tipo di Autenticazione",
    es: "Tipo de Autenticación",
    pl: "Typ uwierzytelniania",
    uk: "Тип автентифікації",
    "zh-cn": "身份验证类型",
  },
  None: {
    en: "None",
    de: "Keine",
    ru: "Никто",
    pt: "Nenhum",
    nl: "Geen",
    fr: "Aucun",
    it: "Nessuna",
    es: "Ninguno",
    pl: "Nic",
    uk: "Жоден",
    "zh-cn": "没有人",
  },
  "Basic Auth": {
    en: "Basic Auth",
    de: "Basic Auth",
    ru: "Базовая аутентификация",
    pt: "Autenticação básica",
    nl: "Basisverificatie",
    fr: "Authentification de base",
    it: "Autenticazione di base",
    es: "Autenticación básica",
    pl: "Podstawowe uwierzytelnianie",
    uk: "Базова аутентифікація",
    "zh-cn": "基本身份验证",
  },
  "Access Token": {
    en: "Access Token",
    de: "Zugangstoken",
    ru: "Маркер доступа",
    pt: "Token de acesso",
    nl: "Toegangstoken",
    fr: "Jeton d'accès",
    it: "Token di accesso",
    es: "Token de acceso",
    pl: "Token dostępu",
    uk: "Токен доступу",
    "zh-cn": "访问令牌",
  },
  Username: {
    en: "Username",
    de: "Benutzername",
    ru: "Имя пользователя",
    pt: "Nome de usuário",
    nl: "Gebruikersnaam",
    fr: "Nom d'utilisateur",
    it: "Nome utente",
    es: "Nombre de usuario",
    pl: "Nazwa użytkownika",
    uk: "Ім'я користувача",
    "zh-cn": "用户名",
  },
  Password: {
    en: "Password",
    de: "Passwort",
    ru: "Пароль",
    pt: "Senha",
    nl: "Wachtwoord",
    fr: "Mot de passe",
    it: "Parola d'ordine",
    es: "Contraseña",
    pl: "Hasło",
    uk: "Пароль",
    "zh-cn": "密码",
  },
  "Click URL": { en: "Click URL", de: "Klick-URL" },
  Tags: { en: "Tags (comma separated)", de: "Tags (kommagetrennt)" },
  "Attachment URL": { en: "Attachment URL", de: "Anhang-URL" },
  "Actions (JSON)": { en: "Actions (JSON)", de: "Aktionen (JSON)" },
  Markdown: { en: "Enable Markdown", de: "Markdown aktivieren" },
  Delay: { en: "Delay (e.g. 1min, 10am)", de: "Verzögerung (z.B. 1min, 10am)" },
};
